title:              All the Miscellaneous Thoughts
tagline:            for anyone or no one to read
description:        A place to put all the miscellaneous thoughts that don't fit anywhere else.
url:                http://kloughra.github.io

author:
  name:             Katie Loughran
  url:              http://kloughra.github.io
  email:            YourName@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
